package com.wom.api.constant;

public enum MainEnum {
	
	CATEGORY("CATEGORY"), PRODUCT("PRODUCT"), USER("USER"), CUSTOMERCART("CUSTOMERCART"), STOCKCONTROL("STOCKCONTROL"),
	STOCKCONTROLHISTORY("STOCKCONTROLHISTORY"), ITEMBUDGETPLANNING("ITEMBUDGETPLANNING"), ITEMBUDGETPLANNINGHISTORY("ITEMBUDGETPLANNINGHISTORY"),
	SUPPLIER("SUPPLIER"), SUPPLIERLIST("SUPPLIERLIST"),SALESORDER("SALESORDER"), SALESORDERDETAILS("SALESORDERDETAILS"), SALESORDERJOBLIST("SALESORDERJOBLIST"), DELIVERYDETAILS("DELIVERYDETAILS"), 
	MAILBOX("MAILBOX"), JOBLIST("JOBLIST"), PURCHASEFUNDING("PURCHASEFUNDING"), PURCHASEFUNDINGHISTORY("PURCHASEFUNDINGHISTORY"),
	PURCHASEAPPROVAL("PURCHASEAPPROVAL"), APPROVERS("APPROVERS"), PURCHASEORDER("PURCHASEORDER"), RECEIVINGINVOICE("RECEIVINGINVOICE"),RECEIVINGDELIVERYORDER("RECEIVINGDELIVERYORDER"),
	PURCHASEORDERJOBLIST("PURCHASEORDERJOBLIST"), RECEIVINGINVOICEJOBLIST("RECEIVINGINVOICEJOBLIST"), VERSION("VERSION"), STOCKPRODUCT("STOCKPRODUCT"), STOCKPRODUCTP("STOCKPRODUCTP"),
	DELIVERYJOBLIST("DELIVERYJOBLIST"), DELIVERYCUSTOMERLIST("DELIVERYCUSTOMERLIST"), CUSTOMERADDRESS("CUSTOMERADDRESS"), STAFF("STAFF"), SYSTEMJOBLIST("SYSTEMJOBLIST"),
	STORE("STORE"), LOGINMAN("LOGINMAN"), LOGINGROC("LOGINGROC"), BOXDELIVERY("BOXDELIVERY"), BOXDELIVERYSCAN("BOXDELIVERYSCAN"), DELIVERY("DELIVERY"), PURCHASEAPPROVED("PURCHASEAPPROVED"),
	ROLEASSIGN("ROLEASSIGN"), ADDRESSINFO("ADDRESSINFO"), CUSTOMER("CUSTOMER"), CREDITCARD("CREDITCARD"), VOUCHER("VOUCHER"), VOUCHERREDEEMED("VOUCHERREDEEMED"), RECHARGEHISTORY("RECHARGEHISTORY"),
	ORDERRECEIPT("ORDERRECEIPT"), PRODUCTNAME("PRODUCTNAME"), SUPPLIERCODE("SUPPLIERCODE"), PRODUCTCODE("PRODUCTCODE"), DELIVERYCOVERAGE("DELIVERYCOVERAGE"), PHOTOCODE("PHOTOCODE"),
	INVOICEPAYABLE("INVOICEPAYABLE"), ACCOUNTTRANSACTION("ACCOUNTTRANSACTION"), INVENTORY("INVENTORY"), PURCHASEREQUEST("PURCHASEREQUEST"), INVENTORYSTOCK("INVENTORYSTOCK"), 
	PURCHASEREQUESTPO("PURCHASEREQUESTPO"), SALESORDERDETAILSBOX("SALESORDERDETAILSBOX"), TRUCKINFO("TRUCKINFO"), INVENTORYJOB("INVENTORYJOB"), INVENTORYTAG("INVENTORYTAG"), PFJOBLIST("PFJOBLIST"), 
	INVENTORYLOC("INVENTORYLOC"),PRODUCTQUOTATION("PRODUCTQUOTATION"), CUSTOMERRECHARGE("CUSTOMERRECHARGE"), INVENTORYMAX("INVENTORYMAX"),
	CUSTOMEREMOBILE("CUSTOMEREMOBILE"), LOGINREG("LOGINREG"), BOXDELIVERYSO("BOXDELIVERYSO"),LOGINFORGOT("LOGINFORGOT"), SALESORDERDETAILSSCANNED("SALESORDERDETAILSSCANNED"),
	SALESORDERDETAILSPROCESS("SALESORDERDETAILSPROCESS"), PURCHASEORDERPRODUCTS("PURCHASEORDERPRODUCTS"), PURCHASEORDERPRODUCTSREJECT("PURCHASEORDERPRODUCTSREJECT"),
	PRODUCTSUPPLIER("PRODUCTSUPPLIER"), SHOPPINGRANK("SHOPPINGRANK"), SHOPPINGRANKLIST("SHOPPINGRANKLIST"), LOGINEDIT("LOGINEDIT"), INVENTORYSO("INVENTORYSO");
	
	private String mainType;
	
	private MainEnum(String mType){
		mainType = mType;
	}
	
	public String getMainType(){
		return mainType;
	}

}
